services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"

  app:
    image: smart-task-manager
    container_name: smart-task-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  frontend:
    image: smart-task-frontend
    container_name: smart-task-frontend
    depends_on:
      - app
    ports:
      - "5173:5173"